name: build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    
      - name: Cloning the code
        uses: actions/checkout@v3

      - name: Start Build
        run: echo "Starting Image Build on dev"

      - name: Run a multi-line script
        run: |
          echo ${API_IMAGE_NAME}
          echo ${FE_IMAGE_NAME}
