name: dev-build

on:
  push:
    branches:
      - dev
      
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      NAME: dev
      
    steps:
      - name: Set Environments
        shell: bash
        id: environments
        run: |
          echo "::set-output name=PYLOT_ENVID::$(echo ${NAME})"

      - name: Print values
        run: echo ${NAME}
