name: dev-build

on:
  push:
    branches:
      - dev
      
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      NAME: dev
      
    steps:
      - name: Set Environments
        shell: bash
        id: environments
        run: |
          echo "::set-output name=MAGENTO_URL::$(echo ${NAME})"
