name: dev-build

on:
  push:
    branches:
      - dev
      
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      NAME: dev
    steps:
      - name: Print values
        run: echo ${NAME}
