name: dev-build

on:
  push:
    branches:
      - dev
      
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      NAME: dev
      ECR_REGION: "us-east-1"
      ECR_REGISTRY_WEBSCALE: "253900346593.dkr.ecr.us-east-1.amazonaws.com"
      ECR_REPOSITORY_NAME_WEBSCALE: "trulieve-test"
    steps:
      - name: Cloning the code
        uses: actions/checkout@v3
        
      - name: Installing the Prereq
        run: |
          sudo apt update && sudo apt install -y jq

      - name: Loging in to Webscale ${NAME} ECR
        run: |
          echo "Configure AWS CLI Profile for user/webscalebuilder USER"
          export AWS_ACCESS_KEY_ID=${{secrets.AWS_KEY}}
          export AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET}}
          export AWS_DEFAULT_REGION=${ECR_REGION}
          aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY_WEBSCALE
          
      - name: Creating Docker Image for ${NAME} 
        run: |
          echo "Creating Docker Image with Webscale API Gateway"
          docker build -t ${ECR_REPOSITORY_NAME_WEBSCALE} .
          
      - name: Pushing the Docker Image to ${NAME} ECR
        run: |
          export AWS_ACCESS_KEY_ID=${{secrets.AWS_KEY}}
          export AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET}}
          export AWS_DEFAULT_REGION=${ECR_REGION}
          export TAG=$(git log -1 --pretty=%h)
          docker tag ${ECR_REPOSITORY_NAME_WEBSCALE}:latest ${ECR_REGISTRY_WEBSCALE}/${ECR_REPOSITORY_NAME_WEBSCALE}:${TAG}
          #docker push $ECR_REGISTRY_WEBSCALE/${ECR_REPOSITORY_NAME_WEBSCALE}:${TAG}
          
